//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerControls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""f5415893-fb98-407a-a145-56856c788e99"",
            ""actions"": [
                {
                    ""name"": ""GamepadMove"",
                    ""type"": ""Button"",
                    ""id"": ""511ffae1-cb23-44aa-910d-4b8b0ba98ee6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""99adf17d-d0b6-4b3e-aa9d-b0e37400b2e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""takeFlashlight"",
                    ""type"": ""Button"",
                    ""id"": ""664b49d9-9a8c-4077-8fe7-37580c26b5b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveFlashlight"",
                    ""type"": ""Button"",
                    ""id"": ""fe0035a9-7a01-4e10-9abb-b6fb18a5b61e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""22d4e098-5190-471b-b8a6-a92103d046eb"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamepadMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef29e0e7-84f6-4bcd-b9cf-3892bf970412"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d1f3d20-b65c-4478-bd34-3fd08ddf43e8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""takeFlashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c6bf7f0-4b4f-4e1f-843c-f9a962ad5b21"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveFlashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_GamepadMove = m_Gameplay.FindAction("GamepadMove", throwIfNotFound: true);
        m_Gameplay_Rotation = m_Gameplay.FindAction("Rotation", throwIfNotFound: true);
        m_Gameplay_takeFlashlight = m_Gameplay.FindAction("takeFlashlight", throwIfNotFound: true);
        m_Gameplay_ActiveFlashlight = m_Gameplay.FindAction("ActiveFlashlight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_GamepadMove;
    private readonly InputAction m_Gameplay_Rotation;
    private readonly InputAction m_Gameplay_takeFlashlight;
    private readonly InputAction m_Gameplay_ActiveFlashlight;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @GamepadMove => m_Wrapper.m_Gameplay_GamepadMove;
        public InputAction @Rotation => m_Wrapper.m_Gameplay_Rotation;
        public InputAction @takeFlashlight => m_Wrapper.m_Gameplay_takeFlashlight;
        public InputAction @ActiveFlashlight => m_Wrapper.m_Gameplay_ActiveFlashlight;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @GamepadMove.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGamepadMove;
                @GamepadMove.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGamepadMove;
                @GamepadMove.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnGamepadMove;
                @Rotation.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotation;
                @takeFlashlight.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTakeFlashlight;
                @takeFlashlight.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTakeFlashlight;
                @takeFlashlight.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnTakeFlashlight;
                @ActiveFlashlight.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnActiveFlashlight;
                @ActiveFlashlight.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnActiveFlashlight;
                @ActiveFlashlight.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnActiveFlashlight;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GamepadMove.started += instance.OnGamepadMove;
                @GamepadMove.performed += instance.OnGamepadMove;
                @GamepadMove.canceled += instance.OnGamepadMove;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @takeFlashlight.started += instance.OnTakeFlashlight;
                @takeFlashlight.performed += instance.OnTakeFlashlight;
                @takeFlashlight.canceled += instance.OnTakeFlashlight;
                @ActiveFlashlight.started += instance.OnActiveFlashlight;
                @ActiveFlashlight.performed += instance.OnActiveFlashlight;
                @ActiveFlashlight.canceled += instance.OnActiveFlashlight;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnGamepadMove(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnTakeFlashlight(InputAction.CallbackContext context);
        void OnActiveFlashlight(InputAction.CallbackContext context);
    }
}
